### ISSUE TITLE
typo in table 3.1

### ISSUE THREAD

**Issue by programandala-net** [GeraldWodni/forth-standard.org#10]
As this is not an issue of the site, but of the original contents, I'm not sure
if this is the right place to inform about it, but anyway, I think there's a
little typo on <http://forth-standard.org/standard/usage#table:datatypes>: the
description of "nest-sys" reads "definitions cells" instead of "definition
call". Right?

**Comment by GeraldWodni** [comment]
Hmm I'd say it is intended to read "definition cells", however it is a valid question and I cannot change the wording of the document without discussion. Luckily I've just finished the contribution function this weekend. May I ask you to register on the website and contribute your question to that document? I'm sure somebody from the committee will answer it.
