### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by programandala-net** [GeraldWodni/forth-standard.org#11]
One link "SAVE-INPUT" is broken on http://forth-standard.org/standard/core/SAVE-INPUT, in the paragraph that starts "After EVALUATE returns...", because the word is divided at the hyphen. But it works on the current PDF version (2014-11-10, page 211).

**Comment by GeraldWodni** [comment]
Thanks for pointing that out. The issue has been fixed in a previous version but i forgot to close it ;)
