### ISSUE TITLE
iForth missing

### ISSUE THREAD

**Issue by mhx-gh** [GeraldWodni/forth-standard.org#12]
"Please let us know if a modern, actively developed system is missing in this list."

iForth is missing.

**Comment by GeraldWodni** [comment]
@mhx-gh indeed! Where should the link point to? Do you have a short one-liner description for iForth?

**Comment by mhx-gh** [comment]
http://home.iae.nl/users/mhx/i4faq.html
iForth is a cross-platform 64-bit Forth with a native code compiler and special parallel extensions. It supports linking to external libraries and has built-in audio and graphics support. The system comes with over 11,000 advanced examples and mini-applications.
