### ISSUE TITLE
Forth tag (topics)

### ISSUE THREAD

**Issue by FForth** [GeraldWodni/forth-standard.org#14]
Please create a "Forth" tag and ... for this project. (Label "Manage topic" in open project)

**Comment by GeraldWodni** [comment]
Sorry I don't understand what you mean. You mean a git-tag? Why?

Please elaborate. Thanks!

**Comment by ruv** [comment]
@GeraldWodni, please have a look at [the manual](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) — the topics describe a repository in GitHub.

**Comment by GeraldWodni** [comment]
Aah I see, a tag on github, I thought a special tag or branch in git was required ;)
@ruv thanks for elaboraing!
