### ISSUE TITLE
Outdated certificate

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#16]
On opening https://forth-standard.org/ a browser shows the following error:

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for forth-standard.org expired on 24 August 2019.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by GeraldWodni** [comment]
Thanks for reporting, I had to manually extend it. Will move to new server soon.
