### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by jkotlinski** [GeraldWodni/forth-standard.org#17]
Firefox warns me that the forth-standard.org certificate has expired. Last weeks I found that the encrypted connection fails intermittently (the lock in URL field is red).

**Comment by GeraldWodni** [comment]
Fixed, thanks for noticing.

I am in the middle of changing infrastructure and forgot that the letsencrypt-renewal is broken on the old server. Be assured that the website will be migrated soon to avoid future problems. SSL will then also be enabled.
