### ISSUE TITLE
The database is disordered after migration

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#19]
After migration of "forth-standard.org" to the new hosting, the contributions are messed up (at least in some web-pages).

For example, the [web-page for `FIND`](https://forth-standard.org/standard/core/FIND) glossary entry shows six proposals that have the same "2018-05-23 17:04:29" timestamp (a [copy](https://archive.is/JGoPt) at the date). An [archived copy ](https://web.archive.org/web/20181008101342/https://forth-standard.org/standard/core/FIND
) (on 2018-10-08) of the web-page contains only one proposal with this timestamp.

Another example, the [web-page for `BUFFER:` ](https://forth-standard.org/standard/core/BUFFERColon) shows two contributions having "2019-07-09 12:54:28" timestamp, three with "2018-09-11 18:09:27", and missed content for contribution "2019-07-06 15:45:25".

**Comment by GeraldWodni** [comment]
@ruv Very good ticket, thanks for making the effort to link the archived copy, saved a lot of time! It seems the view relies on the implicit sorting of the old database, which is different in the cluster. I am on it.
