### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#22]
On navigate to [Login/Sign up](https://forth-standard.org/profile), the web-page shows the following error message:

```
503 Service Unavailable

The service cannot be found in the cluster - we are most likely doing maintenance.
Please try again later.
```

This message is shown since approximately 14:00 UTC on 2020-06-23.

**Comment by GeraldWodni** [comment]
Thanks for reporting, but this is intentional.

I am moving the proposals to their own section (something that has been requested several times). Doing this I cannot allow new replies, otherwise they might end up in the wrong contribution. Will be done soon and reopen then ;)
