### ISSUE TITLE
Some old links are broken

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#23]
### Problem

After moving some contributions to the "proposals" section, the old links are broken.

Example:
The message: https://forth-standard.org/proposals/f-r-and-fr-to-support-dynamically-scoped-floating-point-variables#reply-376
The broken link: https://forth-standard.org/standard/intro#reply-375

![image](https://user-images.githubusercontent.com/2678296/85502714-908a9080-b5f0-11ea-84be-fd72bae23e56.png)

### Possible solution

Generate dummy blocks for the moved contributions in the original places with short information that this contribution was moved, and link to the new place.  Perhaps only for contributions that have incoming links.

The server-side redirection cannot be used since the links contain fragment identifiers (that are not passed to the server).

**Comment by GeraldWodni** [comment]
Forward- and Back-links provided for proposals.
Forward-links provided for replies to proposals.

**Comment by ruv** [comment]
Very nice, thank you!

Just to note (I recalled), an alternative solution would be to fix the links directly in the source XHTML code in the database by means of XSLT or XQury. But, it requires more manual work, and the external inbound links to the moved contributions will stay broken.
