### ISSUE TITLE
Missed context for moved contributions

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#24]
### Problem

Many contributions (that now have been moved into the "proposals" section), was in the context of some glossary entry or section of the standard. And now this context is lost. And the text of contribution can be confusing because of that.

An example of such contribution: https://forth-standard.org/proposals/same-name-token-for-different-words#contribution-136

### Possible solution

Add to the moved contribution an information about the title of the original web-page (and the link to it).

**Comment by GeraldWodni** [comment]
I would ask you to rewrite that proposal using the new template.
You can just reply to it with a new version, and if you want I will then delete the original.

For the other contributions I will consider #23 and you link idea.

#### Explanation:
Although the new procedure states that proposals can be added to words, this behavior is causing some confusion and some vintage Forthers are very unhappy about that. The intention of forth-standard.org is to get more young people into it without alienating the long term folks.

One small example: in Hamburg when discussing your proposal, the question was raised "who is this 'ruv' and why is he not using his real name?". The argument was made that the name does not matter and we carried on, but in usenet most people used their full names.

Some want non-linear discussions, others want to only interface via email.

So this is the small explanation why proposals are now each on their own site and I will add some more features (hopefully diffing) to accommodate the fans of GitHub without alienating the usenet people (too much) ;).

**Comment by GeraldWodni** [comment]
Forward- and Back-links provided for proposals.
Forward-links provided for replies to proposals.

**Comment by ruv** [comment]
@GeraldWodni, thank you for your kindly explanations. And it is an interesting story.
I will rewrite the proposal when time allows.

**Comment by GeraldWodni** [comment]
I think we resolved that already, so I am closing this issue.
