### ISSUE TITLE
Getting the link to a message

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#25]
### Problem

The links to fragment identifiers are very useful for referencing. But they are not explicitly provided at the moment. They can be dug from the HTML source, or from the atom feed.

### Solution

Add an anchor to the date of messages with `href` of the corresponding fragment identifier.

Example: https://forth-standard.org/standard/core/CHAR#reply-212

#### HTML code

Before
```
<span title="UTC" class="created"><i class="fa fa-comments-o"></i> 2019-05-21 02:36:47</span>
```

After
```
<a href="#reply-212">
<time title="UTC" class="created"><i class="fa fa-comments-o"></i> 2019-05-21 02:36:47</time>
</a>
```

**Comment by GeraldWodni** [comment]
I added the link+path to the icon inside the time fragment with a title explaining what this is.

BTW: I value your optimism using the `time`-tag. I used microdata and semantic web years ago, although it all validated I never noticed any difference in SEO or plain searching ;) Let's see what the time-tag can do for us.

**Comment by ruv** [comment]
@GeraldWodni, many thanks!

Regarding `time`-tag — from the microdata and SEO points of view, there is a sense to add `datetime` attribute with date-time in the [machine readable format](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#Valid_datetime_Values).

Regarding the links: they was added into comments only; I think, they should be also added to contributions (i.e., Proposals, Request for clarification, etc).
