### ISSUE TITLE
Wrong reference to the Proposals Process manual.

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#26]
It seems, the web-page https://forth-standard.org/proposals contains a link to the outdated manual "[How to write Forth extension RfDs](http://www.forth200x.org/rfd-guide.html)". The link title: Start by reading **How to write Forth extension RfDs**.

The new manual: https://forth-standard.org/proposals/revised-proposal-process#contribution-71

By the new manual, RfD and RfC terms are no longer used: "A proponent of an extension to the standard writes a **proposal** (previously known as a _request for discussion_ or **RfD**)"

-----

Also, a typo: "New Proc**ee**dure" → "New Procedure"

**Comment by GeraldWodni** [comment]
Good catch, changed all links to the proposed new procedures (I am not sure we accepted them yet, bet they are de-facto standard, so they will be soon if they aren't).

Oh I love that typo, that's a frequent one for me ;)
