### ISSUE TITLE
Undefined web-page name is found

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#29]
Is it OK that some punctuation characters can be added to a glossary webpage address without an error?
E.g.
```
  https://forth-standard.org/standard/core/Colon,,,
  https://forth-standard.org/standard/core/Colon%20,,,
  https://forth-standard.org/standard/core/Colon%20%3E=%3C
```
produce the same web-page as https://forth-standard.org/standard/core/Colon

I would expect error 404.

**Comment by GeraldWodni** [comment]
I think a 404 would be quite harsh if we know what the user wants. So I am now redirecting to a proper id-url, and only return the 404 if this does not match.
