### ISSUE TITLE
Is the login system down?

### ISSUE THREAD

**Issue by mitra42** [GeraldWodni/forth-standard.org#30]
I'm not sure if this is the correct place .... but its where https://forth-standard.org/contact points .

Is the user login system down? 

My profile exists - https://forth-standard.org/~MitraArdron 
but when I try and login as MitraArdron it says: Unknown user 'MitraArdron'

**Comment by GeraldWodni** [comment]
Yes it is, I'm doing maintenance, will be back up soon.

Sorry for the inconvenience :(

**Comment by GeraldWodni** [comment]
@mitra42 login should work again, please confirm.

**Comment by mitra42** [comment]
Confirmed thanks
