### ISSUE TITLE
Unicode symbols are shown wrong

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#39]
In my recent [comment](https://forth-standard.org/standard/core/Cq#reply-804),  in the phrase `a-addr ⇒ c-addr ⇒ addr ⇒ u`, the symbol `⇒` is shown as `?`

Screenshot:
![image](https://user-images.githubusercontent.com/2678296/157037685-9d720484-5fb8-4491-8020-c2c196e12e45.png)

Also, the symbols  `「` and `」` are shown as `?`.

NB: on preview all of them were shown properly.

**Comment by GeraldWodni** [comment]
The character encoding for all tables was set to latin1 (very old decision). :facepalm: 

I updated it all to utf8mb4 and changed your phrase from the screenshot to use the double-arrows.
Please let me know if it no works when you submit a new reply using utf8-symbols.

**Comment by GeraldWodni** [comment]
seems to be working for a while.
