### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by forthy42** [GeraldWodni/forth-standard.org#6]
While it's possible to change the password, it isn't possible to change the user name.

**Comment by GeraldWodni** [comment]
I've changed your name to meet the suggested convention. As I don't think username changes will be frequent, and want to discourage users from changing their names like Facebook-status ;)
So for the moment this will not be implemented.

**Comment by forthy42** [comment]
Suggestion: check for the conventions and warn if the name doesn't follow it...

**Comment by GeraldWodni** [comment]
![thisisforth](https://cloud.githubusercontent.com/assets/3588678/11461114/31d44cd2-96fd-11e5-95cc-7eaa6a4e51a5.jpg)
People will not abide any rules. But maybe a simple regex with a warning icon will do?

**Comment by forthy42** [comment]
No, the "register" button will become "responsive" if the rule is not held.  It will try to avoid the mouse pointer.  If the user is faster than the "register" button, he can still submit ;-).

See for example: https://www.youtube.com/watch?v=duLzGVDlaGY
