### ISSUE TITLE
New implementation of Forth 2012 in Common Lisp

### ISSUE THREAD

**Issue by gmpalter** [GeraldWodni/forth-standard.org#61]
I have just published an implementation of Forth 2012 written in Common Lisp, https://github.com/gmpalter/cl-forth

**Comment by ruv** [comment]
@gmpalter, thank you for your contribution!  You might want to add `forth` and `forth-2012` [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to your GitHub repository.

The [list of Forth systems](https://forth-standard.org/systems) on forth-standard.org is taken from the wiki web-page:
  https://github.com/ForthHub/wiki/wiki/Forth-Systems

Please, add edit this web-page and add you system.

**Comment by gmpalter** [comment]
Thanks for the suggestion about topics. I've added my implementation to the wiki page.
