### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by forthy42** [GeraldWodni/forth-standard.org#8]
The menu bar jumps around oddly when the size changes. Especially the two-line verion seems to be overblown.  A compromise could be smaller font underneath the icons if there's not enough space for the full size font, but more than enough space for the fonts itself.

The navigation (left side) folds up before the "show navigation" button appears, so in between, you have no way to show the navigation.

When you click the "Show navigation", there's no obvious way to hide it again.

The "powered by kern.js" and copyright notice only appears on smaller screens.

**Comment by GeraldWodni** [comment]
The menubar should never be two-lined, I added search and profile without testing the small version, that's where the odd behaviour comes from. Now the text adopts, and it remains one-lines. This also fixes the left navigation.

The copyright notice should always be visible an is on my chrome on linux. Please refresh the page for sure or flush your browser cache. If the error persists can you supply a screenshot or more info about your browser and the resolution the error manifests?
