### ISSUE TITLE
List of Forth communities

### ISSUE THREAD

**Issue by programandala-net** [GeraldWodni/forth-standard.org#9]
I suggest comp.lang.forth and HCC Forth (http://www.forth.hccnet.nl) for the list of communities, and sort all of them by current importance, or alphabetically.

**Comment by GeraldWodni** [comment]
@programandala-net thanks for your suggestions. I think the current sorting should reflect the popularity respectively the number of users.

**Comment by programandala-net** [comment]
En/Je/On 2015-11-30 14:24, GeraldWodni escribió / skribis / wrote :

> I think the current sorting should reflect the popularity respectively
> the number of users.

I agree, that's a good criteria.

I simply was surprised that an active forum like clf is not listed,
while FIG (an useful site that also deserves to be listed) practically
is more an static archive than an actual community.

-- 
Marcos Cruz
http://programandala.net
